name: dart_fundamentos
description: Projeto referente ao curso de Dart fundamentos da Academia do Flutter
version: 1.0.0
homepage: https://academiadoflutter.com.br

environment:
  sdk: '>=2.17.6 <3.0.0'

#dependencies:
 # path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
